<?php
/**
 * SOZO Design
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    SOZO Design
 * @package     Sozo_PureChat
 * @copyright   Copyright (c) 2018 SOZO Design (https://sozodesign.co.uk)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 *
 */
?>
<style>
    #sozo-container {
        background: url('https://sozodesign.co.uk/images/magento/sozo_magento_plugin_about.png') no-repeat scroll 15px #e7efef;
        border: 1px solid #ccc;
        margin: 5px 0;
        padding: 15px 15px 15px 180px;
        min-height: 97px;
    }
</style>
<div id="sozo-container">
    <p>
        <strong>
            SOZO Design PureChat Plugin v<?php echo $this->getVersion() ?>
        </strong> <br>
        Add the PureChat widget to your pages.
        To use this plugin you must have a PureChat account.<br/>
        <a href="http://bit.ly/2tXKIUM" target="_blank" title="Go to PureChat Website">
            Sign Up here to get an account
        </a>
    </p>
    <p>
        Control the look of your Chat window through your
        <a href="https://app.purechat.com" target="_blank">
            PureChat dashboard
        </a>.
    </p>
    <p>
        Website:
        <a href="https://sozodesign.co.uk" target="_blank">sozodesign.co.uk</a><br/>
        Like, share and follow us on
        <a href="https://twitter.com/sozodesign" target="_blank">Twitter</a>,
        <a href="https://plus.google.com/103411336885753828600/" target="_blank">Google+</a>,
        <a href="https://www.youtube.com/user/SozoDesignLtd" target="_blank">YouTube</a>,
        <a href="https://vimeo.com/sozodesign" target="_blank">Vimeo</a>, and
        <a href="http://www.linkedin.com/pub/shaun-uthup/6/785/884" target="_blank">LinkedIn</a>.
    </p>
</div>
